### ISSUE TITLE
Contacting to contribute

### ISSUE THREAD

**Issue by field172** [Alfaa123/Volvo-CAN-Gauge#4]
Hi Alexander - Great exciting work you're doing here! I'm working on a similar project for my volvo with esp32, I'd be happy to contribute.
I'm new to GitHub. 
I have a couple question,and I'm not sure how to collaborate or contribute?

**Comment by Alfaa123** [comment]
Hello,

By far the best way you can contribute to this project is:
- Adding logs from your car
- Looking over existing logs with CAN RE tools and seeing if you can identify any data
- Real-time sniffing in your car to identify data
- Sniffing/logging of VIDA communications with the car for RE purposes

This car has very little documented RE on it's bus systems, so we're basically starting from scratch when it comes to interpreting the CAN frame data.

You are more than welcome to try and port my project over to the ESP32 platform. I don't see why it wouldn't be possible to do with a little bit of effort. I, however, have no personal experience with the ESP32 platform and will not be able to offer much/any assistance.
